symbs = dict([["a", "первый"], ["b", "второй"]])
more_symbs = dict([["c", "третий"], ["d", "четвертый"]])
symbs.update(more_symbs)
print("Словарь:", symbs)
print("Количество ключей в словаре:", len(symbs))
print("Элемент с ключом 'c':", symbs.get("c", "нет такого ключа!"))
print("Наличие элемента с ключом 'c':", "c" in symbs)
del symbs["c"]
print("Словарь:", symbs)
print("Элемент с ключом 'c':", symbs.get("c", "нет такого ключа!"))
print("Наличие элемента с ключом 'c':", "c" in symbs)
print("Ключи словаря:", list(symbs.keys()))
print("Значения элементов словаря:", symbs.values())
print("Содержимое словаря:", list(symbs.items()))
print("Удаляется элемент со значением:", symbs.pop("b"))
print("Словарь:", symbs)
symbs.clear()
print("Словарь:", symbs)
